/**
 * You may override this class to set your own fitness calculation.
 * TODO: describe interface
 *
 * @author DeadbraiN
 */
import Config from './../global/Config';

const FIELDS      = [
    'Date',
    'Calories',
    'Time',
    'Avg HR'
];
const TENNIS      = [
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-26 09:26:26",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 224,
        "Time": "48:39",
        "Avg HR": 102,
        "Max HR": 142,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-25 09:52:07",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 94,
        "Time": "22:20",
        "Avg HR": 95,
        "Max HR": 130,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-22 09:59:11",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 726,
        "Time": "1:58:40",
        "Avg HR": 127,
        "Max HR": 182,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-22 09:07:44",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 77,
        "Time": "12:30",
        "Avg HR": 113,
        "Max HR": 135,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-18 09:11:38",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 240,
        "Time": "58:20",
        "Avg HR": 97,
        "Max HR": 134,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const HOKKEY      = [
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-27 20:10:37",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 373,
        "Time": "1:50:47",
        "Avg HR": 91,
        "Max HR": 138,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-15 20:16:14",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 353,
        "Time": "1:44:38",
        "Avg HR": 92,
        "Max HR": 151,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-05-11 19:29:12",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 546,
        "Time": "1:33:38",
        "Avg HR": 124,
        "Max HR": 171,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-02-06 22:32:12",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 242,
        "Time": "1:30:35",
        "Avg HR": 80,
        "Max HR": 119,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-19 20:24:38",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 357,
        "Time": "2:02:41",
        "Avg HR": 81,
        "Max HR": 137,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const RUNNING     = [
    {
        "Activity Type": "running",
        "Date": "2017-06-29 19:39:57",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.35,
        "Calories": 236,
        "Time": "25:06",
        "Avg HR": 136,
        "Max HR": 180,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:46",
        "Best Pace": "3:26",
        "Elev Gain": 9,
        "Elev Loss": 6,
        "Avg Stride Length": 1.17,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-26 19:56:59",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.04,
        "Calories": 219,
        "Time": "31:09",
        "Avg HR": 116,
        "Max HR": 149,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "7:43",
        "Best Pace": "5:32",
        "Elev Gain": 6,
        "Elev Loss": 2,
        "Avg Stride Length": 1.01,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-24 19:30:47",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 2.96,
        "Calories": 150,
        "Time": "19:45",
        "Avg HR": 121,
        "Max HR": 136,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:40",
        "Best Pace": "5:40",
        "Elev Gain": 4,
        "Elev Loss": 2,
        "Avg Stride Length": 1.01,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-21 19:24:00",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.33,
        "Calories": 246,
        "Time": "23:18",
        "Avg HR": 148,
        "Max HR": 161,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:23",
        "Best Pace": "4:47",
        "Elev Gain": 24,
        "Elev Loss": 24,
        "Avg Stride Length": 1.21,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-20 19:55:30",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 2.01,
        "Calories": 120,
        "Time": "13:04",
        "Avg HR": 135,
        "Max HR": 154,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:31",
        "Best Pace": "5:42",
        "Elev Gain": 15,
        "Elev Loss": 17,
        "Avg Stride Length": 1.02,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const ACTIVITIES  = [TENNIS, HOKKEY, RUNNING];
const ERR_PERCENT = 0.1;
const TOTAL       = ((arr)=>{let sum = 0; arr.forEach((el)=>sum+=el.length);return sum})(ACTIVITIES)
const GOAL        = TOTAL - TOTAL * ERR_PERCENT;

export default class Fitness {
    static run(org) {
        const len = ACTIVITIES.length;

        org.energy = Config.orgStartEnergy;
        for (let i = 0; i < len; i++) {
            this._run(org, ACTIVITIES[i], i);
        }
        //
        // true means that result is found
        //
        return org.energy >= GOAL;
    }

    static compare(org1, org2, maxChanges) {
        const diff = maxChanges / TOTAL;
        return org1.energy * diff * (org1.adds + org1.changes) > org2.energy * diff * (org2.adds + org2.changes);
    }

    static _run(org, data, index) {
        const len  = data.length;
        const code = org.code;
        const vars = code.vars;

        for (let i = 0; i < len; i++) {
            org.mem.length = 0;
            this._setVars(data[i], vars);
            code.run(org);
            org.energy += +(vars[0] === index);
        }
    }

    static _setVars(data, vars) {
        for (let v = 0, len = vars.length; v < len; v++) {
            vars[v] = this._prepareData(FIELDS[v], data[FIELDS[v]]);
        }
    }

    static _prepareData(key, val) {
        if (key === 'Date') {
            let time = val.split(' ')[1].split(':');
            return +time[0] * 3600 + +time[1] * 60 + +time[2];
        }
        if (key === 'Time') {
            let time = val.split(':');
            return time.length > 2 ? time[0] * 3600 + +time[1] * 60 + +time[2] : +time[0] * 60 + +time[1];
        }

        return val;
    }
}