/**
 * You may override this class to set your own fitness calculation.
 * TODO: describe interface
 *
 * @author flatline
 */
const FIELDS      = [
    'Date',
    'Calories',
    'Time',
    'Avg HR'
];
const TENNIS      = [
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-26 09:26:26",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 224,
        "Time": "48:39",
        "Avg HR": 102,
        "Max HR": 142,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-25 09:52:07",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 94,
        "Time": "22:20",
        "Avg HR": 95,
        "Max HR": 130,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-22 11:59:39",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 648,
        "Time": "2:26:17",
        "Avg HR": 108,
        "Max HR": 169,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-22 09:59:11",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 726,
        "Time": "1:58:40",
        "Avg HR": 127,
        "Max HR": 182,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-22 09:07:44",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 77,
        "Time": "12:30",
        "Avg HR": 113,
        "Max HR": 135,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-18 19:08:07",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 491,
        "Time": "1:34:08",
        "Avg HR": 112,
        "Max HR": 151,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-18 09:11:38",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 240,
        "Time": "58:20",
        "Avg HR": 97,
        "Max HR": 134,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-14 19:28:05",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 80,
        "Time": "14:41",
        "Avg HR": 105,
        "Max HR": 135,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-14 17:24:01",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 513,
        "Time": "1:19:30",
        "Avg HR": 123,
        "Max HR": 159,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-14 15:42:09",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 264,
        "Time": "53:34",
        "Avg HR": 105,
        "Max HR": 158,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-14 14:29:46",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 163,
        "Time": "36:17",
        "Avg HR": 99,
        "Max HR": 144,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-12 09:04:04",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 363,
        "Time": "1:10:27",
        "Avg HR": 108,
        "Max HR": 152,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-09 17:02:03",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 328,
        "Time": "1:13:30",
        "Avg HR": 99,
        "Max HR": 152,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-04 09:03:02",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 266,
        "Time": "1:03:38",
        "Avg HR": 98,
        "Max HR": 138,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-21 08:51:41",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 272,
        "Time": "1:24:06",
        "Avg HR": 90,
        "Max HR": 132,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-18 13:43:05",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 110,
        "Time": "1:07:49",
        "Avg HR": 68,
        "Max HR": 106,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-14 09:00:42",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 176,
        "Time": "1:11:32",
        "Avg HR": 80,
        "Max HR": 123,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-12 18:44:59",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 249,
        "Time": "1:14:26",
        "Avg HR": 91,
        "Max HR": 126,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-10 19:19:43",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 205,
        "Time": "49:34",
        "Avg HR": 99,
        "Max HR": 137,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-09 09:00:03",
        "Favorite": "false",
        "Title": "Tennis",
        "Distance": 0,
        "Calories": 281,
        "Time": "1:04:21",
        "Avg HR": 104,
        "Max HR": 146,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const HOKKEY      = [
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-27 20:10:37",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 373,
        "Time": "1:50:47",
        "Avg HR": 91,
        "Max HR": 138,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-13 20:35:33",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 308,
        "Time": "1:24:29",
        "Avg HR": 92,
        "Max HR": 148,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-07-06 21:11:37",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 267,
        "Time": "1:06:04",
        "Avg HR": 97,
        "Max HR": 129,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-15 20:16:14",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 353,
        "Time": "1:44:38",
        "Avg HR": 92,
        "Max HR": 151,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-06-08 20:53:58",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 266,
        "Time": "1:17:18",
        "Avg HR": 92,
        "Max HR": 137,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-05-11 19:29:12",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 546,
        "Time": "1:33:38",
        "Avg HR": 124,
        "Max HR": 171,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-02-09 21:57:27",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 129,
        "Time": "1:00:41",
        "Avg HR": 74,
        "Max HR": 117,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-02-06 22:32:12",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 242,
        "Time": "1:30:35",
        "Avg HR": 80,
        "Max HR": 119,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-02-02 22:41:22",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 292,
        "Time": "1:21:07",
        "Avg HR": 89,
        "Max HR": 133,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-26 21:29:13",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 277,
        "Time": "51:53",
        "Avg HR": 106,
        "Max HR": 139,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-23 20:42:55",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 276,
        "Time": "1:06:15",
        "Avg HR": 96,
        "Max HR": 124,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-19 20:24:38",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 357,
        "Time": "2:02:41",
        "Avg HR": 81,
        "Max HR": 137,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-16 20:26:29",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 569,
        "Time": "1:29:14",
        "Avg HR": 120,
        "Max HR": 166,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2017-01-05 19:58:30",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 428,
        "Time": "2:00:16",
        "Avg HR": 89,
        "Max HR": 138,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-12-29 20:33:01",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 440,
        "Time": "1:24:54",
        "Avg HR": 110,
        "Max HR": 161,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-12-15 20:36:37",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 398,
        "Time": "1:24:44",
        "Avg HR": 106,
        "Max HR": 147,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-12-08 20:16:02",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 266,
        "Time": "1:40:29",
        "Avg HR": 82,
        "Max HR": 133,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-11-10 21:52:24",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 55,
        "Time": "10:52",
        "Avg HR": 99,
        "Max HR": 120,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-11-10 20:25:27",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 316,
        "Time": "1:20:29",
        "Avg HR": 93,
        "Max HR": 128,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "indoor_cardio",
        "Date": "2016-11-03 20:40:32",
        "Favorite": "false",
        "Title": "Hokkey",
        "Distance": 0,
        "Calories": 339,
        "Time": "1:26:42",
        "Avg HR": 92,
        "Max HR": 141,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Speed": "--",
        "Max Speed": "--",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const RUNNING     = [
    {
        "Activity Type": "running",
        "Date": "2017-07-19 20:24:03",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 7.02,
        "Calories": 551,
        "Time": "44:36",
        "Avg HR": 163,
        "Max HR": 173,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:22",
        "Best Pace": "4:53",
        "Elev Gain": 20,
        "Elev Loss": 32,
        "Avg Stride Length": 0.92,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-29 19:39:57",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.35,
        "Calories": 236,
        "Time": "25:06",
        "Avg HR": 136,
        "Max HR": 180,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:46",
        "Best Pace": "3:26",
        "Elev Gain": 9,
        "Elev Loss": 6,
        "Avg Stride Length": 1.17,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-26 19:56:59",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.04,
        "Calories": 219,
        "Time": "31:09",
        "Avg HR": 116,
        "Max HR": 149,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "7:43",
        "Best Pace": "5:32",
        "Elev Gain": 6,
        "Elev Loss": 2,
        "Avg Stride Length": 1.01,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-24 19:30:47",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 2.96,
        "Calories": 150,
        "Time": "19:45",
        "Avg HR": 121,
        "Max HR": 136,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:40",
        "Best Pace": "5:40",
        "Elev Gain": 4,
        "Elev Loss": 2,
        "Avg Stride Length": 1.01,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-21 19:24:00",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.33,
        "Calories": 246,
        "Time": "23:18",
        "Avg HR": 148,
        "Max HR": 161,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:23",
        "Best Pace": "4:47",
        "Elev Gain": 24,
        "Elev Loss": 24,
        "Avg Stride Length": 1.21,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-20 19:55:30",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 2.01,
        "Calories": 120,
        "Time": "13:04",
        "Avg HR": 135,
        "Max HR": 154,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:31",
        "Best Pace": "5:42",
        "Elev Gain": 15,
        "Elev Loss": 17,
        "Avg Stride Length": 1.02,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-05 21:10:12",
        "Favorite": "false",
        "Title": "Ira",
        "Distance": 4.42,
        "Calories": 342,
        "Time": "30:01",
        "Avg HR": 159,
        "Max HR": 173,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:47",
        "Best Pace": "5:14",
        "Elev Gain": 12,
        "Elev Loss": 11,
        "Avg Stride Length": 0.87,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-05 21:09:40",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 0.02,
        "Calories": 1,
        "Time": "0:18.0",
        "Avg HR": 90,
        "Max HR": 108,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "12:43",
        "Best Pace": "5:30",
        "Elev Gain": "--",
        "Elev Loss": 10,
        "Avg Stride Length": 0.86,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-06-01 20:43:18",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 6.32,
        "Calories": 404,
        "Time": "35:02",
        "Avg HR": 158,
        "Max HR": 175,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:33",
        "Best Pace": "4:52",
        "Elev Gain": 19,
        "Elev Loss": 26,
        "Avg Stride Length": 1.19,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-28 21:14:31",
        "Favorite": "false",
        "Title": "Ira",
        "Distance": 4.02,
        "Calories": 300,
        "Time": "26:10",
        "Avg HR": 156,
        "Max HR": 176,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:30",
        "Best Pace": "5:17",
        "Elev Gain": 10,
        "Elev Loss": 26,
        "Avg Stride Length": 0.91,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-28 20:26:49",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 3.41,
        "Calories": 172,
        "Time": "18:20",
        "Avg HR": 138,
        "Max HR": 166,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:22",
        "Best Pace": "4:44",
        "Elev Gain": 8,
        "Elev Loss": 9,
        "Avg Stride Length": 1.22,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-26 10:04:36",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 3.15,
        "Calories": 108,
        "Time": "16:15",
        "Avg HR": 116,
        "Max HR": 151,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:10",
        "Best Pace": "2:06",
        "Elev Gain": 12,
        "Elev Loss": 27,
        "Avg Stride Length": 4.95,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-26 09:58:57",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 0.51,
        "Calories": 13,
        "Time": "2:15.3",
        "Avg HR": 106,
        "Max HR": 111,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "4:27",
        "Best Pace": "2:32",
        "Elev Gain": "--",
        "Elev Loss": 2,
        "Avg Stride Length": 3.97,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-21 12:33:51",
        "Favorite": "false",
        "Title": "Maria run",
        "Distance": 3.02,
        "Calories": 197,
        "Time": "17:45",
        "Avg HR": 163,
        "Max HR": 184,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "5:52",
        "Best Pace": "2:37",
        "Elev Gain": 24,
        "Elev Loss": 24,
        "Avg Stride Length": 1.08,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-05-15 11:06:37",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 1.68,
        "Calories": 121,
        "Time": "11:30",
        "Avg HR": 151,
        "Max HR": 165,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:51",
        "Best Pace": "5:24",
        "Elev Gain": 5,
        "Elev Loss": 21,
        "Avg Stride Length": 0,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-04-09 20:00:20",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 5.88,
        "Calories": 431,
        "Time": "40:05",
        "Avg HR": 153,
        "Max HR": 168,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:49",
        "Best Pace": "5:16",
        "Elev Gain": 16,
        "Elev Loss": 39,
        "Avg Stride Length": 0.86,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-04-09 19:30:27",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 3.31,
        "Calories": 195,
        "Time": "20:45",
        "Avg HR": 141,
        "Max HR": 184,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:16",
        "Best Pace": "4:44",
        "Elev Gain": 9,
        "Elev Loss": 12,
        "Avg Stride Length": 1.14,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-04-05 20:27:07",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 4.2,
        "Calories": 323,
        "Time": "27:23",
        "Avg HR": 161,
        "Max HR": 178,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:31",
        "Best Pace": "3:45",
        "Elev Gain": 15,
        "Elev Loss": 14,
        "Avg Stride Length": 0.89,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "running",
        "Date": "2017-03-29 20:47:38",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 2.64,
        "Calories": 208,
        "Time": "16:46",
        "Avg HR": 164,
        "Max HR": 177,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "6:22",
        "Best Pace": "4:00",
        "Elev Gain": 8,
        "Elev Loss": 10,
        "Avg Stride Length": 0.93,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    },
    {
        "Activity Type": "treadmill_running",
        "Date": "2017-02-17 20:06:50",
        "Favorite": "false",
        "Title": "Untitled",
        "Distance": 0.51,
        "Calories": 47,
        "Time": "3:56.7",
        "Avg HR": 153,
        "Max HR": 178,
        "Aerobic TE": 0,
        "Avg Cadence": "--",
        "Max Cadence": "--",
        "Avg Pace": "7:41",
        "Best Pace": "4:30",
        "Elev Gain": "--",
        "Elev Loss": "--",
        "Avg Stride Length": 1.17,
        "Avg Vertical Ratio": 0,
        "Avg Vertical Oscillation": 0,
        "Avg Ground Contact Time": "--",
        "Avg GCT Balance": "--",
        "Normalized Power® (NP®)": "--",
        "L/R Balance": "--",
        "Training Stress Score®": 0,
        "Max Avg Power (20 min)": "--",
        "Power": "--",
        "Max Power": "--",
        "Total Strokes": "--",
        "Avg. Swolf": "--",
        "Avg Stroke Rate": "--"
    }
];
const ACTIVITIES  = [TENNIS, HOKKEY, RUNNING];
const ERR_PERCENT = 0.1;
const TOTAL       = ((arr)=>{let sum = 0; arr.forEach((el)=>sum+=el.length);return sum})(ACTIVITIES);
const GOAL        = TOTAL - TOTAL * ERR_PERCENT;

class FitnessGarmin {
    static run(org) {
        const len = ACTIVITIES.length;

        org.energy = 0;
        for (let i = 0; i < len; i++) {
            this._run(org, ACTIVITIES[i], i);
        }
        //
        // true means that result is found
        //
        return org.energy >= GOAL;
    }

    static compare(org1, org2, maxChanges) {
        const diff = maxChanges / TOTAL;
        return org1.energy * diff * org1.changes > org2.energy * diff * org2.changes;
    }

    static _run(org, data, index) {
        const len  = data.length;
        const code = org.jsvm;
        const vars = code.vars;

        for (let i = 0; i < len; i++) {
            org.mem.length = 0;
            this._setVars(data[i], vars);
            code.run(org);
            org.energy += +(vars[0] === index);
        }
    }

    static _setVars(data, vars) {
        for (let v = 0, len = vars.length; v < len; v++) {
            vars[v] = this._prepareData(FIELDS[v], data[FIELDS[v]]);
        }
    }

    static _prepareData(key, val) {
        if (key === 'Date') {
            let time = val.split(' ')[1].split(':');
            return +time[0] * 3600 + +time[1] * 60 + +time[2];
        }
        if (key === 'Time') {
            let time = val.split(':');
            return time.length > 2 ? time[0] * 3600 + +time[1] * 60 + +time[2] : +time[0] * 60 + +time[1];
        }

        return val;
    }
}

module.exports = FitnessGarmin;